[package]
name = "wsl-headless-dev"
version = "0.0.1"
edition = "2021"
authors = ["Dmitry Zolotukhin <zlogic@gmail.com>"]
repository = "https://github.com/zlogic/wsl-headless-dev"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "~4.3", features = ["derive"] }
colored = { version = "~2" }
windows = { version = "~0.48", features = ["Win32_System_Power"] }
tokio = { version = "~1.29", default-features = false, features = ["macros", "rt-multi-thread", "sync", "signal", "net"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
